### ISSUE TITLE
Netbox 3.1 support

### ISSUE THREAD

**Issue by hiddenman** [ICTU/netbox_slm#2]
You doc says:

`The Netbox SLM plugin currently only works with v3.0.9 of Netbox due to backwards incompatible changes in newer version of Netbox`

What are these changes? 
We are very interested in such a plugin and would like to help to update and test the plugin with Netbox 3.1 and upcoming 3.2 releases.

**Comment by Hedde** [comment]
@hiddenman I've opened a branch to address these issues https://github.com/ICTU/netbox_slm/tree/feature/netbox-3.1.X-compatibility, there seems to be two issues, of which the latter still has to be addressed

- the deprecation (?) of a base class used by serializers (OrganizationalSerializer)
- i got a template missing error when upgrading to 3.1.X (from 3.0.9) I have to check the name, but I think it was something related to tools/modals.

**Comment by Hedde** [comment]
This issue seems to have been solved by netbox, locally it seems 0.94 works with both 3.0.X and 3.X.X, needs confirmation

**Comment by abhi1693** [comment]
Yesterday, 3.2.0 was released, is the plugin compatible with it?

**Comment by Hedde** [comment]
Fixes have been applied, a tagged release (0.95) is due somewhere in the next couple of days
