### ISSUE TITLE
Add Fields for user assigned/limited licenses

### ISSUE THREAD

**Issue by ff05** [ICTU/netbox_slm#26]
I'd like to store some more information about some licenses
for example a confluence Server License:
number of licensed Users
users currently assigned
as comment: users get there license via ldap group synchronization

or for example volumelicenses:
number of licenses
users currently holding these licenses
as comment: where to find the installer

**Comment by MartVisser** [comment]
Nice to see that you are using or want to start using the plugin!

I can agree with adding the fields:
- 'licence_amount' for volume licences
- 'comments' for any comments about the licence (like other models in Netbox with a nice write/preview mode while adding/changing)

I am not yet convinced about an open field 'users', seems somewhat duplicate to me with the relation to an 'installation'. Perhaps it could be linked to another (to be created) model within Netbox? Or maybe just a field 'license_amount_used' and then the users in the comments field.

**Comment by MartVisser** [comment]
Another option is to arrange it via the custom field functionality within Netbox itself. See https://docs.netbox.dev/en/stable/customization/custom-fields/

I'm going to close this issue due to inactivity. If this is still relevant, please do not hesitate to reopen this issue or submit a PR.
