### ISSUE TITLE
Error to add a license

### ISSUE THREAD

**Issue by jbbenetti** [ICTU/netbox_slm#32]
Hello,
When I try to add a new license for a software product. I have the following message : 
```
Server Error
A database programming error was detected while processing this request. Common causes include the following:

Database migrations missing. When upgrading to a new NetBox release, the upgrade script must be run to apply any new database migrations.
You can run migrations manually by executing python3 manage.py migrate from the command line.

Unsupported PostgreSQL version. Ensure that PostgreSQL version 12 or later is in use.
You can check this by connecting to the database using NetBox's credentials and issuing a query for SELECT VERSION().

The complete exception is provided below:
```

```python
<class 'django.db.utils.ProgrammingError'>

column "stored_location_url" of relation "netbox_slm_softwarelicense" does not exist
LINE 1: ..."name", "description", "type", "stored_location", "stored_lo...
                                                             ^

Python version: 3.11.4
NetBox version: 3.6.3
Plugins: 
  netbox_dns: 0.19.3
  netbox_slm: 1.5
```

However, I have the correct version of Postgres and of the plugin.
I've already seen in another issue that the problem was fixed but in my case, it doesn't work.
In advance, thank you for your answer.

**Comment by wkoot** [comment]
Migrations 0006 and 0007 were not included in the release tar.gz for version v1.5.
I have patched it and released in version v1.5.1, will look at re-releasing v1.5.

**Comment by jbbenetti** [comment]
Thank you for your answer @wkoot.
Finally, I modified the PostgresSQL Database (add a column "cluster_id") and yet it works.
IDEM for softaware installations.

**Comment by MartVisser** [comment]
Just tested 1.5.1 from PyPu with success
