### ISSUE TITLE
SLM Under Different Navigation Field

### ISSUE THREAD

**Issue by rudradevpal** [ICTU/netbox_slm#37]
I have Just Started Using this plugin With Netbox 3.7.5 for managing Licenses in my organisation. Everything looks good and it's a perfect fit for my needs. 
I just have 2 Queries regarding this:
1. How I can Move it to a different Navigation Field? As of now, it's coming under Plugins. Is there any way that I can move it under some different or new field?
![image](https://github.com/ICTU/netbox_slm/assets/28933565/fd010d50-9bf8-4477-bdde-a86e7c1e6d05)

2. When In noebox we are not logged in it Shows the Plugin tab and SLM under this. Anyway to hide this
![image](https://github.com/ICTU/netbox_slm/assets/28933565/1d2e5d2f-a28c-46e4-b7bd-3d1e05d18d1c)

**Comment by MartVisser** [comment]
Hi @rudradevpal

1. I don't think you can adjust this via the GUI. Perhaps by adjusting the code, but this is a plugin after all, so it makes sense for us that it is under 'Plugins'. But suppose we will move it, if possible, what do you think would be a better place? 

2. I think there is a permission check missing on the menu items for the plugin. Can you take a look at this @wkoot? I think a 'permissions' variable is missing on the 'PluginMenuItem' items in netbox_slm/navigation.py.

**Comment by rudradevpal** [comment]
@MartVisser Thanks for the reply.
1. I guess a section called "Software" will be a better option
