### ISSUE TITLE
Compatibility Netbox v4.0.0 and above 

### ISSUE THREAD

**Issue by LeyllProst** [ICTU/netbox_slm#38]
Hello Guys, thanks for this awesome plugin.

May I ask you guys, supporting from Netbox v4.0 are on the table? If it is, do you have planned date for it?
Here is the announce from Netbox team - https://github.com/netbox-community/netbox/releases/tag/v4.0.0

Thanks in advance!

**Comment by MartVisser** [comment]
Hi @LeyllProst 

Cool to hear that you like the plugin! And thanks for the PR!

Support for Netbox 4.x is definitely on the agenda. We will review the PR and if it is sufficient we will merge it. Due to the holiday period, it might take longer but we expect sometime in the next few weeks.
