### ISSUE TITLE
Implement top_level_menu toggle

### ISSUE THREAD

**Issue by Littlericket** [ICTU/netbox_slm#42]
Hi,

would love (in comparison to other plugins) to have the ability to put the SLM on the top level menu instead below plugins.
Many other plugins already support this (as it is easier for navigation, IMHO). Should be a "standard" option for many.

**Comment by MartVisser** [comment]
This appears to be more or less the same as what was requested in issue #37. I'm not certain about the capabilities within Netbox or if it's possible to create a toggle to rearrange items in the menu. Could you reference any existing (open-source) plugins with similar features?
