### ISSUE TITLE
Tweak plugin model

### ISSUE THREAD

**Issue by ryanmerolle** [ICTU/netbox_slm#7]
Possibly get rid of Software Products Model and associate SoftwareProductVersion directly to a platform since software actually links to a platform IE it runs on top of a platform or is the platform.  You could create a list view bubbling up SoftwareVersion to Platform and show software summaries.

I also recommend some rework of the model to include the below fields.

Possible models.py example
```python
class SoftwareVersion(NetBoxModel)
    platform = models.ForeignKey(to="dcim.Platform", on_delete=models.CASCADE, verbose_name="Platform")
    version = models.CharField(max_length=50)
    alias = models.CharField(max_length=50, blank=True, null=True)
    release_date = models.DateField(null=True, blank=True, verbose_name="Release Date")
    end_of_support = models.DateField(null=True, blank=True, verbose_name="End of Software Support")
    documentation_url = models.URLField(blank=True, verbose_name="Documentation URL")
    long_term_support = models.BooleanField(verbose_name="Long Term Support", blank=True, null=True)
    release_type = models.BooleanField(verbose_name="Release Type", default=False)  # Options (Pre-Release, Stable, Feature, etc)
    file_checksum= models.CharField(max_length=200, blank=True, null=True)
    filename = models.CharField(max_length=50, blank=True, null=True)
    file_link = models.URLField(blank=True, verbose_name="File Link")
```

This would allow for something more similar to:

- https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt (I would recommend changing this to a LCM plugin beyond software similar to this plugin)
- https://github.com/goebelmeier/netbox-cisco-support (but vendor agonistic)

**Comment by ryanmerolle** [comment]
I'd be happy to help here if you are open to it.  I was going to tackle this myself, but I rather not build alone.

**Comment by fniessink** [comment]
Hi Ryan, thanks for the suggestion and the offer to help. We'd sure love your help on improving the plugin but as I'm not involved in this plugin as a developer I lack the technical knowledge to review your proposals. The developer who created this plugin is currently on holiday and he will be handing over this project to another developer who will be responsible for maintaining the plugin. In other words, it might take a while before you get a technical response. Feel free to nudge us if you haven't had that response by September 1st.

**Comment by ryanmerolle** [comment]
I’ll look to fork this and submit a PR for review.  I’ll work on this in my leisure.

**Comment by ryanmerolle** [comment]
Has this project been handed over to a new dev that I can work with?

**Comment by fniessink** [comment]
Hi Ryan, Yes, it has, thanks for the reminder. 

Wouter (@wkoot) is the new dev. We also have a product owner, but he is not on GitHub yet I think.

**Comment by ryanmerolle** [comment]
@wkoot any thoughts to my proposed model updates?  Check out the nautobot demo https://demo.nautobot.com/ under the navbar device lifecycle for examples.

I'd love to start slow, prioritize some features to build out, and collaborate. I have [netbox plugin experience](https://github.com/ryanmerolle/netbox-access-lists), and I just want to work to improve your existing rather than go it alone.

Would you like to chat on discord or slack?

**Comment by wkoot** [comment]
It looks like juicy router 2 has a vulnerability! Cool set up you have there, useful dataset too :-)
Personally I haven't worked with NetBox before, we have a set up that seems to be much closer to vanilla.
I will confer with the PO, but let's add on Discord in the meantime. Can you send me your handle?
You can grab my email from one of my commits or just the one listed on [python-instagram](https://github.com/wkoot/python-instagram/blob/master/setup.py)

**Comment by ryanmerolle** [comment]
Ha!  Not my setup.  That is a fork of the NetBox project maintained by Network To Code called Nautobot.  

I mentioned two projects in the original ticket comment.  I can speak more about it as needed.
> * https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt (I would recommend changing this to a LCM plugin beyond software similar to this plugin)
> * https://github.com/goebelmeier/netbox-cisco-support (but vendor agonistic)

Hmm I must be dense, but I do not see the handle.  I'm also on the [NetBox slack](https://netdev.chat/) which is likely useful for you given the support you can find there.  For slack and discord, my handle is the same as my github handle.

**Comment by ryanmerolle** [comment]
@wkoot any other way I can reach out?

**Comment by MartVisser** [comment]
Hi @ryanmerolle, I am the new product owner for this plugin from our organization. Perhaps we could create a group chat together with @wkoot in Microsoft Teams? If you are active on Microsoft Teams I will need your email address.

**Comment by ryanmerolle** [comment]
I am not.

I am on the netbox slack and discord.

**Comment by ryanmerolle** [comment]
I have not seen a ton of movement, do you all need help?

If anything comes up you need help with or want someone to bounce ideas off of let me know.  I am on [https://netdev.chat](https://netdev.chat) with the same username

**Comment by deku-m** [comment]
I wonder, is there still updates on this plugin?
Would be great to see it mature like the https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt.

**Comment by ryanmerolle** [comment]
ping

**Comment by wkoot** [comment]
It's still on the radar guys :-) I haven't gotten around to finishing #3 yet, as it needs a different approach. But for this year there's more time allotted. Any merge requests submitted are welcome and will receive attention however!

**Comment by MartVisser** [comment]
I'm going to close this issue due to inactivity. We will look into #9. If this is still relevant, please do not hesitate to reopen this issue or submit a PR.
