### ISSUE TITLE
Add software license to software installation

### ISSUE THREAD

**Issue by eric-nieuwland** [ICTU/netbox_slm#8]
Please add the ability to register the software license used for a software installation.
Preferably, allow for the software license to be shared among installations.

License would include:
- kind/type (e.g. GPL, CC, single payment, repeated payment)
- expiration date that can be queried (including NULL iff not paid license)

NOTE Actual license keys should *not* be stored here. They should be kept in a separate secure place. A reference to that place could be included here.

**Comment by MartVisser** [comment]
Suggested fields and links to other models:
- Software Version (Link to Software Version model)
- Type
- Start Date (Optional)
- Expiration Date (Optional)
- Installation (Link to Software Installation model)
- Stored Location (Where is the license key stored? - Maybe create a separate model for this)
